In [1]:
# perkalian matriks array

import numpy as np

A = np.array([[0,8],[1,2],[7,1]])
B = np.array([[4,4],[2,0],[6,1]])

perkalian = A * B
print(perkalian)

[[ 0 32]
 [ 2  0]
 [42  1]]


In [5]:
# pengurangan matriks array

import numpy as np

A = np.array([[0,8],[1,2],[7,1]])
B = np.array([[4,4],[2,0],[6,1]])

pengurangan = A - B
print(pengurangan)

[[-4  4]
 [-1  2]
 [ 1  0]]


In [4]:
# transpose matriks array

import numpy as np 
A = np.array([[0,8],[1,2],[7,1]])

transpose_A = np.transpose(A)
print(transpose_A)

[[0 1 7]
 [8 2 1]]


In [3]:
# invers matriks array

import numpy as np

A = np.array([[1,2],[7,1]])

invers_A = np.linalg.inv(A)
print("\ninvers matriks A:")
print("invers dari matriks A:", invers_A)


invers matriks A:
invers dari matriks A: [[-0.07692308  0.15384615]
 [ 0.53846154 -0.07692308]]


In [2]:
# determinan matriks array

import numpy as np
A = np.array([[1,2],[7,1]])

determinant_A = np.linalg.det(A)
print("determinan dari matriks A:", determinant_A)

determinan dari matriks A: -13.0
